language: python
python:
- 3.5.6
install:
- pipenv install
script: py.test --cov=tests
deploy:
  provider: openshift
  user: Lwando92
  password:
    secure: qAvClDZm388sBdhB+2cQ+4OEySU+Fiw/TWYmUqukEufiR/bNTjh2ik93fokOuHChNkGufCN1DdjhmjoTzPf4S1xX5qlKNsL8QInPM8JJ8rs0RbMGeOkZzh10wmGcs18DIky3dxrgE52AcudlVGqb0vtYmfCF+KpRzlC3m1GvCg0r9dsxbTsx2T4jAhCef5+0SrCVeKdpkfW/TpwH3/OWfKcCWbgWD8W+Mt6s/1yZvi7ZxiGfhAGITyTTteyieLD2IxHOohLM4PaZ1VIyRpJIH2Cin9JitepSpgWeLAvHA1gSy2rQ6WPWxv22sGChjmMlWJFLWE4os+WJ1UaOzyLMgWyaG6DnED/aZMI8D7wEY8l6BL1hx0E+nzjNavnCUCsnoCPDALWtc8UTwHVuKYZqaOdW9gWWJwezlSiVXtCCszfFijFHewZ/fQI86h6W2mhiRTfs/+yd3aaYRClOCOIcqF0Ww8Edud34kY+Bgszfcctf9Nds/H1bIwW7pah9BYHLMga11IsV8Oqwcdtr2RsrWNN3PZpS6LJdBtsEE9mBvGCUIvv94+nR/onpxrkduBQfTKBo/RifCdVArP4qo5kJmugWdcTsAVrC0rb90eMhSFIyQS17t7f8xurETxS9+4mHLWee9uiYj/KdlCVa2MsyJB4DxNa8hFt7VbJxqIdd5QE=
  app: FlaskApp
  domain: flaskapplication
  on:
    repo: nonzulu/FlaskApp
